### ISSUE TITLE
Waiting for day 2 :-)

### ISSUE THREAD

**Issue by Obijuan** [adumont/AlexForth6809#1]
I can't wait for day 2!!! Your journal is amazing. I have to say that reading day 1, AT LAST, I've understood a lof of concepts about Forth. There are many books out there, but they always speak in a very abstract way...mixing a lot of concepts. But in your case, with the implementation of the simple forth program "1 1 +", I've seen the light... Thank you very very much

I am totally hooked on your tutorial, waiting for more... (just like a jonkie 🤣️🤣️)

Keep up the good work, and Thanks a lot for sharing it

**Comment by adumont** [comment]
See 0da318abaf60f29aa1762690a0af6ac596b34981.

[Day 2: Colon defined Words and Return Stack!](https://github.com/adumont/AlexForth6809/blob/main/docs/day02/README.md)

**Comment by Obijuan** [comment]
Thanks a lot! 😀😀😀
